# Generated by Django 4.2.6 on 2023-11-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(editable=False)),
                ('account_balance', models.DecimalField(decimal_places=3, max_digits=6)),
                ('account_type', models.CharField(choices=[('Savings', 'savings'), ('Current', 'current')], max_length=50)),
                ('account_status', models.CharField(choices=[('Active', 'active'), ('Closed', 'closed'), ('Frozen', 'frozen')], max_length=50)),
                ('fixed_deposit', models.CharField(choices=[('Regular', 'regular'), ('Senior Citizen', 'senior citizen'), ('Corporate', 'corporate')], max_length=50)),
                ('transfer_pin', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musironbank.account')),
            ],
        ),
    ]
