# Generated by Django 4.2.7 on 2023-11-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musironbank', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='musiron', max_length=50),
        ),
    ]
